#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    lst = s.split(" ")
    capitalized = []
    for i in range(len(lst)):
        c = lst[i].capitalize()
        capitalized.append(c)
    return " ".join(capitalized)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
